# global-gitignore.ps1 — agents installer: global gitignore setup (Windows)
#
# Adds a managed block to %XDG_CONFIG_HOME%\git\ignore (or ~\.config\git\ignore)
# so that WORKTREE_NOTES.md files generated by /worktree-start are globally
# ignored without modifying any per-repo .gitignore.
#
# Idempotent: re-running replaces the managed block; never duplicates it.
# Aborts on corrupted markers (BEGIN without END, etc.).
# Usage: called from install.ps1, or directly as .\install\win\global-gitignore.ps1

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$BlockBegin = "# --- BEGIN agents-managed ---"
$BlockEnd   = "# --- END agents-managed ---"
$BlockContent = @(
    $BlockBegin,
    "# WORKTREE_NOTES.md (generated by /worktree-start skill)",
    "WORKTREE_NOTES.md",
    $BlockEnd
)

# Resolve gitignore path via XDG or fallback
$XdgCfg = if ($env:XDG_CONFIG_HOME) { $env:XDG_CONFIG_HOME } else { Join-Path $HOME ".config" }
$GitIgnorePath = Join-Path $XdgCfg "git" "ignore"
$GitIgnorePath = [System.IO.Path]::GetFullPath($GitIgnorePath)

# Validate target is not a directory
if (Test-Path $GitIgnorePath -PathType Container) {
    Write-Error "global-gitignore.ps1: '$GitIgnorePath' is a directory, not a file."
    exit 1
}

# Ensure parent directory exists
$Parent = Split-Path $GitIgnorePath -Parent
if (-not (Test-Path $Parent)) {
    New-Item -ItemType Directory -Path $Parent -Force | Out-Null
}

# If file doesn't exist, create with just our block
if (-not (Test-Path $GitIgnorePath -PathType Leaf)) {
    $BlockContent | Set-Content -Path $GitIgnorePath -Encoding UTF8
    Write-Host "global-gitignore.ps1: created '$GitIgnorePath' with agents-managed block."
    exit 0
}

$Lines = Get-Content $GitIgnorePath -Raw -Encoding UTF8
$AllLines = if ($Lines) { $Lines -split "`n" | ForEach-Object { $_.TrimEnd("`r") } } else { @() }

$BeginCount = ($AllLines | Where-Object { $_ -eq $BlockBegin }).Count
$EndCount   = ($AllLines | Where-Object { $_ -eq $BlockEnd   }).Count

if ($BeginCount -gt 1 -or $EndCount -gt 1) {
    Write-Error "global-gitignore.ps1: duplicate agents-managed markers in '$GitIgnorePath'. Repair manually and re-run."
    exit 1
}
if ($BeginCount -eq 1 -and $EndCount -eq 0) {
    Write-Error "global-gitignore.ps1: BEGIN marker without END in '$GitIgnorePath'. Repair manually."
    exit 1
}
if ($BeginCount -eq 0 -and $EndCount -eq 1) {
    Write-Error "global-gitignore.ps1: END marker without BEGIN in '$GitIgnorePath'. Repair manually."
    exit 1
}

if ($BeginCount -eq 1 -and $EndCount -eq 1) {
    # Replace existing block
    $NewLines = [System.Collections.Generic.List[string]]::new()
    $Skip = $false
    foreach ($line in $AllLines) {
        if ($line -eq $BlockBegin) { $Skip = $true; continue }
        if ($line -eq $BlockEnd)   { if ($Skip) { $Skip = $false; continue } }
        if (-not $Skip) { $NewLines.Add($line) }
    }
    # Trim trailing blank lines added by awk equivalent, then append block
    while ($NewLines.Count -gt 0 -and $NewLines[-1] -eq "") { $NewLines.RemoveAt($NewLines.Count - 1) }
    if ($NewLines.Count -gt 0) { $NewLines.Add("") }
    $NewLines.AddRange([string[]]$BlockContent)
    $NewLines | Set-Content -Path $GitIgnorePath -Encoding UTF8
    Write-Host "global-gitignore.ps1: updated agents-managed block in '$GitIgnorePath'."
    exit 0
}

# No existing block — append
$Existing = (Get-Content $GitIgnorePath -Raw -Encoding UTF8) ?? ""
if ($Existing -and -not $Existing.EndsWith("`n")) {
    Add-Content -Path $GitIgnorePath -Value "" -Encoding UTF8
}
$BlockContent | Add-Content -Path $GitIgnorePath -Encoding UTF8
Write-Host "global-gitignore.ps1: appended agents-managed block to '$GitIgnorePath'."
