# session-sync-init.ps1 - Initialize ~/.claude/projects as a git repo for session sync
# Usage: Called by install.ps1, or manually: .\session-sync-init.ps1

param(
    [string]$ClaudeDir = (Join-Path $env:USERPROFILE ".claude"),
    [string]$RemoteUrl = "",
    [switch]$NoRemote
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$defaultRemote = "git@github.com:nirecom/agent-sessions.git"
if (-not $NoRemote -and -not $RemoteUrl) {
    $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
    $envFile = Join-Path (Split-Path -Parent (Split-Path -Parent $scriptDir)) ".env"
    if (Test-Path $envFile) {
        $envLine = Get-Content $envFile | Where-Object { $_ -match '^SESSION_SYNC_REMOTE_URL=' } | Select-Object -First 1
        if ($envLine) { $RemoteUrl = ($envLine -split '=', 2)[1].Trim('"').Trim("'") }
    }
    if (-not $RemoteUrl) { $RemoteUrl = $defaultRemote }
}

if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
    Write-Warning "Git is required for session sync."
    return
}

$ProjectsDir = Join-Path $ClaudeDir "projects"
if (-not (Test-Path $ProjectsDir)) { New-Item -ItemType Directory -Path $ProjectsDir -Force | Out-Null }

if (Test-Path (Join-Path $ClaudeDir ".git")) {
    Write-Host "Migrating git root from $ClaudeDir to $ProjectsDir..."
    Remove-Item (Join-Path $ClaudeDir ".git") -Recurse -Force
    Remove-Item (Join-Path $ClaudeDir ".gitignore") -Force -ErrorAction SilentlyContinue
    Remove-Item (Join-Path $ClaudeDir ".gitattributes") -Force -ErrorAction SilentlyContinue
}

if (-not (Test-Path (Join-Path $ProjectsDir ".git"))) {
    Write-Host "Initializing git repo in $ProjectsDir..."
    git init $ProjectsDir
} else {
    Write-Host "Git repo already exists in $ProjectsDir." -ForegroundColor DarkGray
}
git -C $ProjectsDir config core.hooksPath NUL

$gitattributesContent = @"
# All files under this repo are machine-generated by Claude Code
* text eol=lf
*.jsonl merge=union
"@
[System.IO.File]::WriteAllText((Join-Path $ProjectsDir ".gitattributes"), ($gitattributesContent -replace "`r`n", "`n") + "`n")

$gitignoreContent = "/workflow/*.tmp`n"
[System.IO.File]::WriteAllText((Join-Path $ProjectsDir ".gitignore"), $gitignoreContent)

if (-not $NoRemote) {
    $existingRemotes = git -C $ProjectsDir remote 2>$null
    if ($existingRemotes -contains "origin") {
        git -C $ProjectsDir remote set-url origin $RemoteUrl
    } else {
        git -C $ProjectsDir remote add origin $RemoteUrl
    }
    Write-Host "Remote set to $RemoteUrl"
}

Write-Host "Session sync initialized." -ForegroundColor Green
