"use strict";
// hooks/lib/plan-sync/allowlist.js
// What plan-sync may publish: the rendered .gitignore (an allowlist over the
// registry's synced plan-artifact names) and the per-file sync-target predicate.
const path = require("path");
const { parsePlansEntry, planArtifactNames } = require("../plans-artifact-registry");

const SYNCED_NAMES = new Set(planArtifactNames());

function renderGitignore() {
  const lines = [
    "# Generated by plan-sync (bin/plan-sync-init); do not edit by hand.",
    "/*",
    ...planArtifactNames().map((name) => `!/*-${name}`),
    "/.*",
    "!/.gitignore",
  ];
  return `${lines.join("\n")}\n`;
}

// isSyncTarget(plansDir, absPath) — true only for a direct child of plansDir whose
// basename parses as a synced plan artifact (drafts/, dot entries and outside paths are false).
function isSyncTarget(plansDir, absPath) {
  if (typeof plansDir !== "string" || typeof absPath !== "string" || !plansDir || !absPath) return false;
  const rel = path.relative(path.resolve(plansDir), path.resolve(absPath));
  if (!rel || rel.startsWith("..") || rel.includes("/") || rel.includes("\\") || rel.startsWith(".")) {
    return false;
  }
  return isSyncTargetName(rel);
}

// isSyncTargetName(rel) — the same predicate on a repo-relative path (tree entries).
function isSyncTargetName(rel) {
  if (typeof rel !== "string" || !rel || rel.includes("/") || rel.includes("\\") || rel.startsWith(".")) {
    return false;
  }
  const parsed = parsePlansEntry(rel);
  return Boolean(parsed && parsed.verdict === "artifact" && parsed.kind === "plan-artifact"
    && SYNCED_NAMES.has(parsed.name));
}

module.exports = { renderGitignore, isSyncTarget, isSyncTargetName };
