#!/usr/bin/env bash
# Tests: hooks/block-capture-echo/remedy.js, install/settings-allow-commands.txt
# Tags: capture-echo-guard, remedy-wording, ssot-match, degradation, error-cases, scope:issue-specific, pwsh-not-required
# Section C2 — the allowlist file itself is unusable (#2170 review gap C9).
# part3 covers lists whose ENTRIES are hostile; this file covers lists that carry no
# usable entry at all. readSsotEntries answers null for each, and buildRemedy must then
# take the SAME generic branch c it takes when AGENTS_CONFIG_DIR is unset — never crash,
# and never fall through to a branch that names a sanctioned entry point.

set -uo pipefail

# TL3 gap (what this test does NOT catch):
# - a real allowlist file made unreadable by ACL rather than by shape (see the
#   CPR-UNV note at C-19c: chmod 000 is a no-op for an elevated Windows account)
# - how the degraded wording renders inside a live Claude Code permission prompt
# Closest-to-action mitigation: this gap is checked at WORKFLOW_USER_VERIFIED preflight
# via bin/check-verification-gate.sh category: hook-registration.

AGENTS_DIR="${1:-$(cd "$(dirname "$0")/../.." && pwd)}"
export AGENTS_DIR
DRIVER="$(cd "$(dirname "$0")" && pwd)/remedy-driver.js"
command -v node >/dev/null 2>&1 || exit 77

PASS=0
FAIL=0

assert_eq() {
    local name="$1" want="$2" got="$3"
    if [ "$want" = "$got" ]; then
        echo "PASS: $name"; PASS=$((PASS + 1))
    else
        echo "FAIL: $name — want=$(printf '%q' "$want") got=$(printf '%q' "$got")"; FAIL=$((FAIL + 1))
    fi
}

TMPDIR_C2="$(mktemp -d)"
trap 'rm -rf "$TMPDIR_C2"' EXIT

# Same two classifiers as part3, so a branch verdict means the same thing in both files.
classify() {
    local out="$1"
    case "$out" in
        MODULE_MISSING|EXPORT_MISSING|THREW:*) printf '%s' "$out"; return ;;
    esac
    local low bare=0 scratch=0
    low="$(printf '%s' "$out" | tr '[:upper:]' '[:lower:]')"
    case "$low" in *bare*) bare=1 ;; esac
    case "$low" in *scratchpad*) scratch=1 ;; esac
    if [ "$bare" -eq 1 ] && [ "$scratch" -eq 1 ]; then printf 'both'
    elif [ "$bare" -eq 1 ]; then printf 'bare-only'
    elif [ "$scratch" -eq 1 ]; then printf 'scratchpad-only'
    else printf 'neither'
    fi
}
has_substr() {
    case "$1" in
        MODULE_MISSING|EXPORT_MISSING|THREW:*) printf '%s' "$1" ;;
        *"$2"*) printf 'yes' ;;
        *) printf 'no' ;;
    esac
}
run_remedy() { env AGENTS_CONFIG_DIR="$1" node "$DRIVER" "$2" 2>&1; }
RECIPE='Reissue it as a single bare command:'
PROBE='bash "$AGENTS_CONFIG_DIR/bin/good"'

# Every fixture ships the SAME sibling `bin/good` with a bash shebang, so the probe
# command would reach branch a if the list were usable. A "both" verdict can therefore
# only mean the LIST was rejected — not that the command missed.
mk_cfg() {
    mkdir -p "$1/install" "$1/bin"
    printf '#!/usr/bin/env bash\necho ok\n' >"$1/bin/good"
}

EMPTY_CFG="$TMPDIR_C2/cfg-empty-list"
mk_cfg "$EMPTY_CFG"
: >"$EMPTY_CFG/install/settings-allow-commands.txt"

COMMENT_CFG="$TMPDIR_C2/cfg-comments-only"
mk_cfg "$COMMENT_CFG"
printf '# generated by install/gen-settings-allow.js\n\n#   bin/good\n' \
    >"$COMMENT_CFG/install/settings-allow-commands.txt"

# Unreadable by SHAPE, not by ACL: a directory standing in the file's place makes
# readFileSync throw EISDIR on every platform, whereas chmod 000 is a no-op for an
# elevated Windows account and would turn this row green for the wrong reason
# (CPR-UNV: no environment assumption).
UNREAD_CFG="$TMPDIR_C2/cfg-unreadable-list"
mk_cfg "$UNREAD_CFG"
rmdir "$UNREAD_CFG/install" 2>/dev/null || true
mkdir -p "$UNREAD_CFG/install/settings-allow-commands.txt"

for row in "C-19a-empty-list:$EMPTY_CFG" \
           "C-19b-comments-only-list:$COMMENT_CFG" \
           "C-19c-unreadable-list:$UNREAD_CFG"; do
    OUT="$(run_remedy "${row#*:}" "$PROBE")"
    assert_eq "${row%%:*}-degrades-to-generic" "both" "$(classify "$OUT")"
    assert_eq "${row%%:*}-no-bare-recipe" "no" "$(has_substr "$OUT" "$RECIPE")"
done

# Positive control for the whole file: the identical fixture layout WITH one real entry
# reaches branch a, so the three degradations above are the list CONTENT and not the
# fixture (protection-fix-tests.md Pattern 4).
GOOD_CFG="$TMPDIR_C2/cfg-one-real-entry"
mk_cfg "$GOOD_CFG"
printf '# a comment line, then one real entry\nbin/good\n' \
    >"$GOOD_CFG/install/settings-allow-commands.txt"
OUT="$(run_remedy "$GOOD_CFG" "$PROBE")"
assert_eq "C-19d-one-real-entry-control" "bare-only" "$(classify "$OUT")"
assert_eq "C-19e-control-names-the-entry" "yes" "$(has_substr "$OUT" "bin/good")"

echo ""
echo "Section C2: PASS=$PASS FAIL=$FAIL"
exit "$FAIL"
