#!/bin/bash
# install/linux/install.sh — agents installer: global gitignore setup
#
# Adds a managed block to ~/.config/git/ignore (XDG_CONFIG_HOME/git/ignore)
# so that WORKTREE_NOTES.md files generated by /worktree-start are globally
# ignored without modifying any per-repo .gitignore.
#
# Idempotent: re-running replaces the managed block; never duplicates it.
# Aborts with non-zero exit if the gitignore has corrupted markers (BEGIN without END, etc.).

set -euo pipefail

BLOCK_BEGIN="# --- BEGIN agents-managed ---"
BLOCK_END="# --- END agents-managed ---"

# Resolve gitignore path via XDG or fallback
_gitignore_path() {
    local xdg_cfg="${XDG_CONFIG_HOME:-${HOME}/.config}"
    printf '%s/git/ignore' "$xdg_cfg"
}

# Write the managed block content to stdout
_block_content() {
    printf '%s\n' \
        "$BLOCK_BEGIN" \
        "# WORKTREE_NOTES.md (generated by /worktree-start skill)" \
        "WORKTREE_NOTES.md" \
        "$BLOCK_END"
}

main() {
    local target
    target="$(_gitignore_path)"

    # Validate target is not a directory
    if [ -d "$target" ]; then
        echo "install.sh: error: '$target' is a directory, not a file." >&2
        exit 1
    fi

    # Ensure parent directory exists (fail clearly if not writable)
    local parent
    parent="$(dirname "$target")"
    if [ ! -d "$parent" ]; then
        mkdir -p "$parent" || { echo "install.sh: error: cannot create '$parent'." >&2; exit 1; }
    fi
    if [ ! -w "$parent" ] && [ ! -f "$target" ]; then
        echo "install.sh: error: parent directory '$parent' is not writable." >&2
        exit 1
    fi

    # If file doesn't exist, create it with just our block
    if [ ! -f "$target" ]; then
        _block_content > "$target"
        echo "install.sh: created '$target' with agents-managed block."
        return 0
    fi

    # Check write permission on existing file
    if [ ! -w "$target" ]; then
        echo "install.sh: error: '$target' is not writable." >&2
        exit 1
    fi

    # Count existing markers to detect corruption
    local begin_count end_count
    begin_count="$(grep -c "^${BLOCK_BEGIN}$" "$target" 2>/dev/null || true)"
    end_count="$(grep -c "^${BLOCK_END}$" "$target" 2>/dev/null || true)"

    if [ "$begin_count" -gt 1 ] || [ "$end_count" -gt 1 ]; then
        echo "install.sh: error: duplicate agents-managed markers in '$target'." >&2
        echo "  BEGIN count: $begin_count, END count: $end_count" >&2
        echo "  Repair manually and re-run." >&2
        exit 1
    fi

    if [ "$begin_count" -eq 1 ] && [ "$end_count" -eq 0 ]; then
        echo "install.sh: error: BEGIN marker without END in '$target'. Repair manually." >&2
        exit 1
    fi

    if [ "$begin_count" -eq 0 ] && [ "$end_count" -eq 1 ]; then
        echo "install.sh: error: END marker without BEGIN in '$target'. Repair manually." >&2
        exit 1
    fi

    if [ "$begin_count" -eq 1 ] && [ "$end_count" -eq 1 ]; then
        # Replace existing block using awk (works without GNU sed -i on all POSIX systems)
        local tmp
        tmp="$(mktemp)" || { echo "install.sh: error: cannot create temp file." >&2; exit 1; }
        awk -v begin="$BLOCK_BEGIN" -v end="$BLOCK_END" '
            /^# --- BEGIN agents-managed ---$/ { skip=1; next }
            /^# --- END agents-managed ---$/ { if (skip) { skip=0; next } }
            !skip { print }
        ' "$target" > "$tmp"
        # Ensure trailing newline before appending block
        if [ -s "$tmp" ]; then
            local last_char
            last_char="$(tail -c1 "$tmp" | wc -c)"
            if [ "$last_char" -gt 0 ]; then
                # Check if file ends with newline
                if [ "$(tail -c1 "$tmp" | od -An -tx1 | tr -d ' \n')" != "0a" ]; then
                    printf '\n' >> "$tmp"
                fi
            fi
        fi
        _block_content >> "$tmp"
        mv "$tmp" "$target"
        echo "install.sh: updated agents-managed block in '$target'."
        return 0
    fi

    # No existing block — append (with leading newline if file not empty and doesn't end with newline)
    if [ -s "$target" ]; then
        if [ "$(tail -c1 "$target" | od -An -tx1 | tr -d ' \n')" != "0a" ]; then
            printf '\n' >> "$target"
        fi
    fi
    _block_content >> "$target"
    echo "install.sh: appended agents-managed block to '$target'."
}

main "$@"
