#!/bin/bash
# session-sync-init.sh - Initialize ~/.claude/projects as a git repo for session sync
# Usage: Called by install.sh, or manually: ./session-sync-init.sh

set -euo pipefail

if [ -z "${C_RESET+x}" ]; then
    if [ -t 1 ]; then
        C_GREEN='\033[0;32m'; C_GRAY='\033[0;90m'; C_RESET='\033[0m'
    else
        C_GREEN=''; C_GRAY=''; C_RESET=''
    fi
fi

CLAUDE_DIR="$HOME/.claude"
_DEFAULT_REMOTE="git@github.com:nirecom/agent-sessions.git"
REMOTE_URL=""
NO_REMOTE=false

while [ $# -gt 0 ]; do
    case "$1" in
        --claude-dir) CLAUDE_DIR="$2"; shift 2 ;;
        --remote-url) REMOTE_URL="$2"; shift 2 ;;
        --no-remote) NO_REMOTE=true; shift ;;
        *) shift ;;
    esac
done

# Resolve remote URL: --remote-url arg > .env > default
if [ -z "$REMOTE_URL" ] && ! "$NO_REMOTE"; then
    _script_dir="$(cd "$(dirname "$0")" && pwd)"
    _env_file="$(cd "$_script_dir/../.." && pwd)/.env"
    if [ -f "$_env_file" ]; then
        _env_val=$(grep -E '^SESSION_SYNC_REMOTE_URL=' "$_env_file" | head -1 | cut -d= -f2- | tr -d "\"'")
        [ -n "$_env_val" ] && REMOTE_URL="$_env_val"
    fi
    REMOTE_URL="${REMOTE_URL:-$_DEFAULT_REMOTE}"
fi

if ! type git >/dev/null 2>&1; then
    echo "Git is required for session sync." >&2
    exit 1
fi

PROJECTS_DIR="$CLAUDE_DIR/projects"
mkdir -p "$PROJECTS_DIR"

_changed=false

# Migrate old git root from ~/.claude/ to ~/.claude/projects/
if [ -d "$CLAUDE_DIR/.git" ]; then
    echo "Migrating git root from $CLAUDE_DIR to $PROJECTS_DIR..."
    rm -rf "$CLAUDE_DIR/.git"
    rm -f "$CLAUDE_DIR/.gitignore" "$CLAUDE_DIR/.gitattributes"
    _changed=true
fi

if [ ! -d "$PROJECTS_DIR/.git" ]; then
    echo "Initializing git repo in $PROJECTS_DIR..."
    git init "$PROJECTS_DIR"
    _changed=true
else
    printf "${C_GRAY}Git repo already exists in $PROJECTS_DIR.${C_RESET}\n"
fi
git -C "$PROJECTS_DIR" config core.hooksPath /dev/null

_attrs_content='# All files under this repo are machine-generated by Claude Code
* text eol=lf
*.jsonl merge=union
'
_attrs_path="$PROJECTS_DIR/.gitattributes"
if [ ! -f "$_attrs_path" ] || [ "$(cat "$_attrs_path")" != "$_attrs_content" ]; then
    printf '%s' "$_attrs_content" > "$_attrs_path"
    _changed=true
fi

_ignore_content='/workflow/*.tmp
'
_ignore_path="$PROJECTS_DIR/.gitignore"
if [ ! -f "$_ignore_path" ] || [ "$(cat "$_ignore_path")" != "$_ignore_content" ]; then
    printf '%s' "$_ignore_content" > "$_ignore_path"
    _changed=true
fi

if ! "$NO_REMOTE"; then
    _existing=$(git -C "$PROJECTS_DIR" remote 2>/dev/null || true)
    if echo "$_existing" | grep -qx "origin"; then
        _current_url=$(git -C "$PROJECTS_DIR" remote get-url origin 2>/dev/null || true)
        if [ "$_current_url" != "$REMOTE_URL" ]; then
            git -C "$PROJECTS_DIR" remote set-url origin "$REMOTE_URL"
            printf "${C_GREEN}Remote updated to $REMOTE_URL${C_RESET}\n"
            _changed=true
        fi
    else
        git -C "$PROJECTS_DIR" remote add origin "$REMOTE_URL"
        printf "${C_GREEN}Remote set to $REMOTE_URL${C_RESET}\n"
        _changed=true
    fi
fi

if [ "$_changed" = "true" ]; then
    printf "${C_GREEN}Session sync initialized.${C_RESET}\n"
else
    printf "${C_GRAY}Session sync already up to date.${C_RESET}\n"
fi
