#!/usr/bin/env bash
# tests/TL3-installer-rtk-config-create-contract.sh
# Tests: install/win/rtk.ps1, install/linux/rtk.sh
# Tags: TL3, rtk, installer, config, scope:issue-specific
#
# Real-binary contract for the `rtk config` / `rtk config --create` seam the
# installers rely on after retiring install/lib/rtk-config-deploy.js: config
# exits 0 on absent/valid/obsolete-but-parseable, non-zero on unparseable TOML,
# and --create repairs unparseable and migrates obsolete configs to the default.

set -uo pipefail

AGENTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
. "$AGENTS_DIR/tests/lib/harness.sh"

# TL3 gap (what this test does NOT catch):
# - Windows-native path (rtk.ps1 via winget, %LOCALAPPDATA% resolution, bounded poll) --
#   this bash test runs on Linux/macOS only; Windows paths are marked pwsh-required
# - rtk.ps1 / rtk.sh installer orchestration (ordering, conditional create call) --
#   installer script stub/mock testing is out of scope per intent.md; TL3 direct binary test
# Closest-to-action mitigation: pwsh-required category fires at WORKFLOW_USER_VERIFIED preflight

# Skip-gate 1: get-config-var must be usable.
[ -x "$AGENTS_DIR/bin/get-config-var" ] || { echo "SKIP: $AGENTS_DIR/bin/get-config-var not found or not executable" >&2; exit 77; }

# Skip-gate 2: RUN_TL3 must be explicitly on (rules/test/claude-e2e.md).
if "$AGENTS_DIR/bin/get-config-var" --is-off RUN_TL3 off; then
  echo "SKIP: requires RUN_TL3=on in .env" >&2; exit 77
fi

# Skip-gate 3: the real rtk binary must be on PATH.
command -v rtk >/dev/null 2>&1 || { echo "SKIP: rtk CLI not found on PATH" >&2; exit 77; }

# --- Fixture isolation (rules/test/fixture-isolation.md) --------------------
# harness.sh already unset CLAUDE_SESSION_ID/CLAUDE_CODE_SESSION_ID/CLAUDE_ENV_FILE.
unset CLAUDE_WORKFLOW_DIR
unset WORKFLOW_PLANS_DIR

FIXTURE_HOME="$(make_tmp)"
trap 'rm -rf "$FIXTURE_HOME"' EXIT

# Pin every home/config anchor rtk might resolve at the fixture. On Linux/macOS
# the dirs crate honors XDG_CONFIG_HOME/HOME; on Windows it reads the OS known
# folder and ignores these -- the containment check below then skips (TL3 gap).
export HOME="$FIXTURE_HOME"
export USERPROFILE="$FIXTURE_HOME"
export XDG_CONFIG_HOME="$FIXTURE_HOME"
export APPDATA="$FIXTURE_HOME"
export LOCALAPPDATA="$FIXTURE_HOME"

# run_rtk: run `rtk <args>` under a timeout, silence output, echo the exit code.
run_rtk() {
  if run_with_timeout 60 rtk "$@" >/dev/null 2>&1; then
    echo 0
  else
    echo $?
  fi
}

# --- Containment verification (once, before any destructive op) -------------
# 1. Pre-write read-only check: the fixture must hold no config file yet.
EXISTING="$(find "$FIXTURE_HOME" -type f 2>/dev/null)"
if [ -n "$EXISTING" ]; then
  echo "SKIP: fixture home already contains files before probe: $EXISTING" >&2; exit 77
fi

# Windows pre-skip: RTK's dirs crate ignores env var pins on Windows.
# Must exit BEFORE calling the probe to avoid mutating the live user config.
case "$(uname -s 2>/dev/null || true)" in
  CYGWIN*|MINGW*|MSYS*)
    echo "SKIP: Windows host: RTK dirs crate ignores env var pins; skipping before probe" >&2; exit 77 ;;
esac
if [ -n "${WINDIR:-}" ] || [ -n "${SystemRoot:-}" ]; then
  echo "SKIP: Windows host: RTK dirs crate ignores env var pins; skipping before probe" >&2; exit 77
fi

# 2. First and only write probe: this single --create both probes containment
#    and generates Case C's valid config.
CREATE_EXIT="$(run_rtk config --create)"
if [ "$CREATE_EXIT" -ne 0 ]; then
  echo "SKIP: rtk config --create probe exited $CREATE_EXIT (cannot establish fixture)" >&2; exit 77
fi

# 3. Containment check (read-only): the generated config must land under the
#    fixture home. The fixture was empty, so any file found now is rtk's.
FIXTURE_CONFIG_PATH="$(find "$FIXTURE_HOME" -type f -name '*.toml' 2>/dev/null | head -n1)"
if [ -z "$FIXTURE_CONFIG_PATH" ]; then
  FIXTURE_CONFIG_PATH="$(find "$FIXTURE_HOME" -type f 2>/dev/null | head -n1)"
fi
if [ -z "$FIXTURE_CONFIG_PATH" ]; then
  echo "SKIP: rtk config --create wrote no file under \$FIXTURE_HOME -- PIN ignored, aborting destructive ops" >&2; exit 77
fi

# --- Case C: valid config (already generated by the probe) ------------------
C_EXIT="$(run_rtk config)"
[ "$C_EXIT" -eq 0 ] && pass "Case C: rtk config exits 0 on generated valid config" \
  || fail "Case C: rtk config expected exit 0 on valid config, got $C_EXIT"

BEFORE_RECREATE="$(cat "$FIXTURE_CONFIG_PATH" 2>/dev/null)"
C_RECREATE_EXIT="$(run_rtk config --create)"
[ "$C_RECREATE_EXIT" -eq 0 ] && pass "Case C: rtk config --create is idempotent (exit 0 on valid config)" \
  || fail "Case C: rtk config --create expected exit 0 on re-run, got $C_RECREATE_EXIT"

AFTER_RECREATE="$(cat "$FIXTURE_CONFIG_PATH" 2>/dev/null)"
[ "$BEFORE_RECREATE" = "$AFTER_RECREATE" ] && pass "Case C: valid config unchanged by idempotent --create" \
  || fail "Case C: --create modified an already-valid config"

# --- Case A: unparseable config rejected, then repaired by --create --------
# rtk config's reject verdict fires on a TOML syntax error, not on a parseable
# but obsolete schema (Case D). Both verdicts are covered (CPR-ORTH).
printf 'this is = = broken [[[ not toml\n' > "$FIXTURE_CONFIG_PATH"
A_EXIT="$(run_rtk config)"
[ "$A_EXIT" -ne 0 ] && pass "Case A: rtk config exits non-zero on unparseable TOML" \
  || fail "Case A: rtk config expected non-zero on unparseable TOML, got $A_EXIT"

A_CREATE_EXIT="$(run_rtk config --create)"
[ "$A_CREATE_EXIT" -eq 0 ] && pass "Case A: rtk config --create repairs unparseable config (exit 0)" \
  || fail "Case A: rtk config --create expected exit 0 repairing config, got $A_CREATE_EXIT"

A_AFTER_EXIT="$(run_rtk config)"
[ "$A_AFTER_EXIT" -eq 0 ] && pass "Case A: rtk config exits 0 after repair" \
  || fail "Case A: rtk config expected exit 0 after repair, got $A_AFTER_EXIT"

# --- Case D: obsolete schema tolerated on read, migrated by --create --------
# `[retriever]` is the retired v<0.48 schema. It parses, so `rtk config` exits 0;
# `rtk config --create` rewrites it to the current valid default (content changes).
OBSOLETE='[retriever]
enabled = false'
printf '%s\n' "$OBSOLETE" > "$FIXTURE_CONFIG_PATH"
D_READ_EXIT="$(run_rtk config)"
[ "$D_READ_EXIT" -eq 0 ] && pass "Case D: rtk config exits 0 on parseable obsolete schema" \
  || fail "Case D: rtk config expected exit 0 on obsolete schema, got $D_READ_EXIT"

D_CREATE_EXIT="$(run_rtk config --create)"
D_AFTER="$(cat "$FIXTURE_CONFIG_PATH" 2>/dev/null)"
[ "$D_CREATE_EXIT" -eq 0 ] && pass "Case D: rtk config --create exits 0 migrating obsolete schema" \
  || fail "Case D: rtk config --create expected exit 0 migrating, got $D_CREATE_EXIT"

# Version-agnostic validity check: verify the new config is valid, not absent.
# Avoid hard-coding schema content (e.g. [retriever] absent) since RTK's defaults
# evolve across versions; the binary's own 'rtk config' is the authoritative validator.
D_VALID_EXIT="$(run_rtk config)"
[ "$D_VALID_EXIT" -eq 0 ] && pass "Case D: --create migrated obsolete schema to a valid default" \
  || fail "Case D: post-migration config is invalid (rtk config exit $D_VALID_EXIT)"
[ -n "$D_AFTER" ] && pass "Case D: --create wrote non-empty config" \
  || fail "Case D: --create left config empty instead of migrating"

# --- Case B: absent/empty config falls back to built-in defaults ------------
# The "no create needed" branch: rtk config must succeed WITHOUT a prior --create.
# B1: absent (no file)
rm -f "$FIXTURE_CONFIG_PATH"
B_EXIT="$(run_rtk config)"
[ "$B_EXIT" -eq 0 ] && pass "Case B: rtk config exits 0 on absent config (built-in defaults, no --create)" \
  || fail "Case B: rtk config expected exit 0 on absent config, got $B_EXIT"

# B2: empty file — the installer premise that an empty config is treated as absent.
# The rtk.ps1/rtk.sh code path for 'rtk config' exits 0 and skips --create in this case.
printf '' > "$FIXTURE_CONFIG_PATH"
B2_EXIT="$(run_rtk config)"
[ "$B2_EXIT" -eq 0 ] && pass "Case B: rtk config exits 0 on empty config file (built-in defaults)" \
  || fail "Case B: rtk config expected exit 0 on empty config, got $B2_EXIT"

echo "Results: PASS=$PASS FAIL=$FAIL"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
